# Generated by Django 4.2.1 on 2023-05-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='administrador',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
    ]
