# Generated by Django 4.2.1 on 2023-06-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_comentario_usuario_alter_entrada_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
