# Generated by Django 4.2.1 on 2023-06-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_pelicula_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='valoracion',
            field=models.FloatField(null=True, verbose_name='Valoracion'),
        ),
    ]
