# Generated by Django 4.2.1 on 2023-06-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_pelicula_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='butaca',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
